library("data.table")
dtime <- difftime(as.POSIXct("2007-02-03"), as.POSIXct("2007-02-01"),units="mins")
rowsToRead <- as.numeric(dtime)
DT <- fread("household_power_consumption.txt", skip="1/2/2007", nrows = rowsToRead, na.strings = c("?", ""))
DT$datetime <- as.POSIXct(paste(DT$V1,DT$V2), format="%d/%m/%Y %H:%M:%S")
plot(DT$datetime,DT$V3, type = "n", xlab = "",ylab = "Global Active Power(kilowatts)")
with(DT,lines(DT$datetime,DT$V3, lty = 1))
dev.copy(device = png, file = "plot2.png")
dev.off()
